# Generated by Django 5.0 on 2023-12-07 14:47

from django.contrib.auth.models import Group
from django.db import migrations

from services.group_service import get_group_name_coach, get_group_name_student
from users.models import User


def add_default_users_and_groups(apps, schema_editor):
    Group.objects.bulk_create([
        Group(name=get_group_name_coach()),
        Group(name=get_group_name_student())
    ])

    User.objects.bulk_create([
        User(
            email='max.mustermann@coach.com',
            firstname='Max',
            lastname='Mustermann'
        ),
        User(
            email='hulda.musterfrau@coach.com',
            firstname='Hulda',
            lastname='Musterfrau'
        ),
        User(
            email='martin.knecht@student.com',
            firstname='Martin',
            lastname='Knecht'
        ),
        User(
            email='larissa.brunner@student.com',
            firstname='Larissa',
            lastname='Brunner'
        ),
    ])

    for user in User.objects.filter(email__in=['max.mustermann@coach.com', 'hulda.musterfrau@coach.com']):
        user.groups.add(Group.objects.get(name=get_group_name_coach()))
        user.save()

    for user in User.objects.filter(email__in=['martin.knecht@student.com', 'larissa.brunner@student.com']):
        user.groups.add(Group.objects.get(name=get_group_name_student()))
        user.save()


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_default_users_and_groups),
    ]
