# Generated by Django 5.0 on 2024-03-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_aim_check', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actioncompetence',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='checklearnaim',
            name='comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='learnaim',
            name='description',
            field=models.TextField(),
        ),
    ]
