# Generated by Django 5.0 on 2024-04-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_aim_check', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actioncompetence',
            name='title',
            field=models.TextField(),
        ),
    ]
