# Generated by Django 5.0 on 2024-02-20 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learn_aim_check', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actioncompetence',
            name='education_ordinance',
            field=models.ManyToManyField(to='users.educationordinance'),
        ),
        migrations.AddField(
            model_name='checklearnaim',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checklearnaim',
            name='assigned_trainee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='learnaim',
            name='action_competence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn_aim_check.actioncompetence'),
        ),
        migrations.AddField(
            model_name='checklearnaim',
            name='closed_learn_check',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn_aim_check.learnaim'),
        ),
        migrations.AddField(
            model_name='learnaim',
            name='tags',
            field=models.ManyToManyField(to='learn_aim_check.tags'),
        ),
    ]
