# Generated by Django 5.0 on 2024-05-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_aim_check', '0002_alter_actioncompetence_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklearnaim',
            name='marked_as_todo',
            field=models.BooleanField(default=False),
        ),
    ]
