# Generated by Django 5.0 on 2024-05-15 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_aim_check', '0003_checklearnaim_marked_as_todo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklearnaim',
            name='marked_as_todo',
        ),
        migrations.AddField(
            model_name='learnaim',
            name='marked_as_todo',
            field=models.BooleanField(default=False),
        ),
    ]
